# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "80c01f7c1ffa0f2a36b49bb87c30e143"
application_url = "https://rage-naturals-mm-continental.trycloudflare.com"
embedded = true
name = "aliexpress"
handle = "aliexpress-41"

[build]
include_config_on_deploy = true
dev_store_url = "paymenttest-store.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_locales,read_products,read_script_tags,read_themes,write_content,write_locales,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://rage-naturals-mm-continental.trycloudflare.com/auth/callback",
  "https://rage-naturals-mm-continental.trycloudflare.com/auth/shopify/callback",
  "https://rage-naturals-mm-continental.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
